// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkhemONOxEUQkF1EaD5l_117xvpiQ3XSY',
    appId: '1:1068755837459:web:37f113e57b1350c65e95e6',
    messagingSenderId: '1068755837459',
    projectId: 'tunecrate-9aa7f',
    authDomain: 'tunecrate-9aa7f.firebaseapp.com',
    storageBucket: 'tunecrate-9aa7f.firebasestorage.app',
    measurementId: 'G-SWTG0EGDF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2g98lmbM-gvFNqHxF-isJqGbCGaX_8sA',
    appId: '1:1068755837459:android:cb9836a2dfe2c9505e95e6',
    messagingSenderId: '1068755837459',
    projectId: 'tunecrate-9aa7f',
    storageBucket: 'tunecrate-9aa7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9bQvJFf9t1cTd3Ez3RYN-1vosnZu_vs0',
    appId: '1:1068755837459:ios:ae08c487c19490b75e95e6',
    messagingSenderId: '1068755837459',
    projectId: 'tunecrate-9aa7f',
    storageBucket: 'tunecrate-9aa7f.firebasestorage.app',
    iosBundleId: 'com.example.tunecrate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9bQvJFf9t1cTd3Ez3RYN-1vosnZu_vs0',
    appId: '1:1068755837459:ios:ae08c487c19490b75e95e6',
    messagingSenderId: '1068755837459',
    projectId: 'tunecrate-9aa7f',
    storageBucket: 'tunecrate-9aa7f.firebasestorage.app',
    iosBundleId: 'com.example.tunecrate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkhemONOxEUQkF1EaD5l_117xvpiQ3XSY',
    appId: '1:1068755837459:web:fd656307a3c8d2e15e95e6',
    messagingSenderId: '1068755837459',
    projectId: 'tunecrate-9aa7f',
    authDomain: 'tunecrate-9aa7f.firebaseapp.com',
    storageBucket: 'tunecrate-9aa7f.firebasestorage.app',
    measurementId: 'G-N2BBRWKL6C',
  );
}
